Repository SpiritSeal/bubblemap, pull requests merged in 2022-10, with the labels that each got.

#70 Edited Pref Dialog scope to persist past SideMenu
  src/pages/MindMap/overlays/SideMenu/SettingsButton.tsx
  src/pages/MindMap/overlays/SideMenu/SettingsDialog.tsx
  src/pages/MindMap/overlays/SideMenu/SideMenu.tsx
Labels: enhancement

#58 Adding and Removing Nodes
  functions/package-lock.json
  functions/package.json
  package-lock.json
  package.json
  src/components/Routing/index.tsx
  src/index.tsx
  src/pages/MindMap/Bubble.tsx
  src/pages/MindMap/BubbleLink.tsx
  src/pages/MindMap/MindMapSimulation.tsx
  src/pages/MindMap/index.tsx
  src/pages/MindMap/overlays/SideMenu/SettingsButton.tsx
  src/pages/MindMap/overlays/SideMenu/SideMenu.tsx
  src/pages/MindMap/overlays/TestFunctionButton/TestFunctionButton.tsx
  src/types.ts
Labels: enhancement

#114 Add User Auth
  functions/package-lock.json
  package-lock.json
  package.json
  src/components/Routing/index.tsx
  src/components/Routing/mindmapRouter.tsx
  src/pages/CreateAccount/index.tsx
  src/pages/Home/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/MindMap/index.tsx
  src/pages/SignIn/index.tsx
Labels: enhancement

#116 Manage MindMaps Page
  functions/package-lock.json
  functions/package.json
  package-lock.json
  package.json
  src/components/Loading/index.tsx
  src/components/Navigation/index.tsx
  src/components/Routing/index.tsx
  src/pages/Home/index.tsx
  src/pages/ManageMindMaps/ShareDialog/index.tsx
  src/pages/ManageMindMaps/index.tsx
  src/pages/MindMap/Bubble.tsx
  src/pages/MindMap/MindMapSimulation.tsx
  src/pages/MindMap/index.tsx
  src/pages/MindMap/overlays/SideMenu/SideMenu.tsx
  src/types.ts
Labels: enhancement

#119 Add User Input Triggers
  package-lock.json
  package.json
  src/pages/MindMap/Bubble.tsx
  src/pages/MindMap/MindMapSimulation.tsx
  src/pages/MindMap/index.tsx
Labels: enhancement

#124 Theming and Consistency
  package-lock.json
  package.json
  public/index.html
  src/components/Dialogs/ConfirmationDialog/index.tsx
  src/contexts/MUITheme.tsx
  src/pages/CreateAccount/index.tsx
  src/pages/ManageMindMaps/index.tsx
  src/pages/MindMap/Bubble.css
  src/pages/MindMap/Bubble.tsx
  src/pages/MindMap/BubbleLink.tsx
  src/pages/MindMap/BubbleText.txt
  src/pages/MindMap/overlays/SideMenu/SideMenu.css
  src/pages/MindMap/overlays/SideMenu/SideMenu.tsx
Labels: enhancement

#138 Add User Account Page & Anonymous Authentication
  .env.production
  .firebaserc
  .github/workflows/cd.yml
  .github/workflows/preview.yml
  firebase.json
  package-lock.json
  package.json
  src/components/ClaimAccount/index.tsx
  src/components/Routing/index.tsx
  src/pages/Account/AddAuthMethod.tsx
  src/pages/Account/ChangeEmail.tsx
  src/pages/Account/ChangeName.tsx
  src/pages/Account/ChangePassword.tsx
  src/pages/Account/index.tsx
  src/pages/Home/index.tsx
Labels: enhancement

#140 UI Improvements
  .env
  .env.development
  .env.production
  .github/CONTRIBUTING.md
  .gitignore
  README.md
  public/index.html
  public/manifest.json
  src/App.tsx
  src/components/Navigation/index.tsx
  src/components/Routing/index.tsx
  src/pages/Home/index.tsx
  src/pages/MindMap/Bubble.tsx
  src/pages/MindMap/BubbleLink.tsx
  src/pages/MindMap/MindMap.css
  src/pages/MindMap/MindMapSimulation.tsx
  src/pages/MindMap/index.tsx
  src/pages/MindMap/overlays/BottomBar/KeyBindsDialog.css
  src/pages/MindMap/overlays/BottomBar/KeyBindsDialog.tsx
  src/pages/MindMap/overlays/BottomBar/index.tsx
  src/pages/MindMap/overlays/BottomRightButtons/index.tsx
  src/pages/MindMap/overlays/GenIdeaPanel/index.tsx
  src/pages/MindMap/overlays/SideMenu/DrawerListItem.tsx
  src/pages/MindMap/overlays/SideMenu/SettingsButton.tsx
  src/pages/MindMap/overlays/SideMenu/SettingsDialog.tsx
  src/pages/MindMap/overlays/SideMenu/SideMenu.tsx
  src/pages/MindMap/overlays/TestFunctionButton/TestFunctionButton.tsx
Labels: bug, enhancement

#148 Sharing & Security
  firestore.rules
  functions/package-lock.json
  functions/package.json
  functions/src/summarize/summarizeDump.txt
  package-lock.json
  package.json
  public/robots.txt
  src/components/Routing/index.tsx
  src/pages/Home/index.tsx
  src/pages/ManageMindMaps/ShareDialog/index.tsx
  src/pages/ManageMindMaps/index.tsx
  src/pages/MindMap/MindMapSimulation.tsx
  src/pages/MindMap/index.tsx
  src/types.ts
Labels: bug, enhancement, Core

#152 Auth Improvements
  firestore.indexes.json
  public/assets/logos/Simple Bubble Map Logo.png
  public/assets/logos/apple-touch-icon.png
  public/index.html
  src/App.tsx
  src/components/ClaimAccount/index.tsx
  src/components/Navigation/index.tsx
  src/components/Routing/AnonymousAuth.tsx
  src/components/Routing/index.tsx
  src/pages/Home/index.tsx
Labels: bug, enhancement, Core
