Repository SpiritSeal/bubblemap, pull requests merged in 2022-09, with the labels that each got.

#7 Fix Unclickable Button in Mind Map
  src/components/Routing/index.tsx
Labels: bug

#13 Fix Node Dragging
  functions/package-lock.json
  functions/package.json
  package-lock.json
  package.json
  src/App.test.tsx
  src/pages/MindMap/Bubble.tsx
  src/pages/MindMap/MindMapSimulation.tsx
Labels: bug, enhancement

#17 Update GitHub Workflows
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .github/workflows/firebase-hosting-testing-merge.yml
  .github/workflows/preview.yml
  firebase.json
  package-lock.json
  package.json
  remoteconfig.template.json
Labels: enhancement

#14 Openai config
  functions/src/ai/ai.ts
  functions/src/ai/secrets/note_to_eric.txt
Labels: bug

#34 Fix Root Node Formatting
  .env.production
  .firebaserc
  .github/workflows/preview.yml
  firebase.json
  src/pages/MindMap/Bubble.tsx
Labels: bug

#46 Standardize Idea Gen Function
  functions/package-lock.json
  functions/src/ai/ai.ts
  package-lock.json
Labels: enhancement

#53 Refactor Canvas Zoom and Pan to use SVG Viewports and Viewboxes
  functions/package-lock.json
  functions/package.json
  package-lock.json
  package.json
  public/manifest.json
  src/index.tsx
  src/pages/MindMap/MindMap.css
  src/pages/MindMap/MindMapSimulation.tsx
Labels: bug, enhancement

#69 Create Test Function Button
  src/pages/MindMap/index.tsx
  src/pages/MindMap/overlays/SideMenu/SettingsButton.tsx
  src/pages/MindMap/overlays/SideMenu/SideMenu.tsx
  src/pages/MindMap/overlays/TestFunctionButton/TestFunctionButton.tsx
  src/types.ts
Labels: enhancement
